### ISSUE TITLE
Teleport Equipment

### ISSUE THREAD

**Issue by mzegar** [mzegar/sbox-TTT#22]
**Describe the bug**
Use SWB to make teleporter equipment, ignore any view models for now.

"The teleporter is very useful for escaping from sticky situations. The teleporter can be bought as a weapon in slot 8 for traitors and detectives alike. If you want to use the teleporter, you MUST remeber to mark a location with right-click first, the use left-click to teleport there. If you are standing on solid ground, pressing right-click will result in a message display in the top-right corner that says "teleport location successfully marked." if you are crouching, standing on a prop, in the air, or even not on solid ground, you wil get a message reading the reason why the location mark failed. You can mark a teleport location as many times as you like. When it comes to teleporting to the location, you have only 16 uses but those 16 uses can be very useful if you be sure no one knows that you used it. When you teleport you will be forced to stand still for a few seconds while the teleporting commences. After the teleportation, there will be a rather large glass mark on the ground placed whre you teleported to and from. There is no way of telling who teleported just from the mark so you are safe there. The disguiser can go very good with the teleporter, as you can deactivate the disguise after teleporting away to a secret place. The teleporter can also be used to trick your enemies or just confuse them. Getting out of traps such as drowning rooms or falling buildings can be very useful for detectives using it. If you are the detective and you have a teleporter at the same time someone is drowning on the map ttt_67thway, you can throw the teleported through the door and they can teleport to the location that you previously marked. As well, if a traitor had marked a teleport location in a traitor room, you can teleport there as any previously marked location."

**Comment by youarereadingthis** [comment]
Most people won't read anything this long especially during active gameplay but it would be neat to have a handbook with this detail while you're dead. There are a lot of finer points with equips people may not have thought of.

Otherwise it should be kept to three or so short sweet lines.

**Comment by Fires1** [comment]
I like on screen tool tips and will always always always vouch for complex/easy to forget control mechanisms to be on the bottom of the screen. Handbook might not be a bad idea as an expansion upon TTT1's original 'how to play the game' powerpoint within the F1 menu.

**Comment by mzegar** [comment]
I just gave the long description since someone wanted to work on this. I had no intention of having this anywhere ingame. Just as a guide for whoever wanted to take this on. I'm going to close this since we are currently reworking the entire weapon structure and don't want anyone's time to go to waste.
