### ISSUE TITLE
Discord Inviation Link expired

### ISSUE THREAD

**Issue by neolectron** [mzegar/sbox-TTT#346]
Hello, I've noticed that in the README and on your webiste, the [discord](https://discord.com/invite/rrsrakF8N3) link is dead.
![image](https://github.com/CigarLounge/sbox-TTT/assets/5268400/fe5b73f6-e006-4569-a2b6-a92ea7fe5bae)

Also, I've noticed that the link to the github repository on the asset.party website is also expired.
It points to your personnal github repo instead of CigarLounge one.
![image](https://github.com/CigarLounge/sbox-TTT/assets/5268400/c9eaaadc-853b-4063-b6c7-effb93a5224a)

Thank you for mod, I'm learning s&box dev with it, and it's been a pleasure so far.
Cheers.

**Comment by matekdev** [comment]
Project is no longer active, you can use this repo (if you follow the license), or this repo since it uses a MIT license https://github.com/matekdev/sbox-TTT

**Comment by neolectron** [comment]
Okay thank you, I think I will fork the repository as-well because the new one you linked me is already an archive xddd
