### ISSUE TITLE
Rewrite IEntityHint

### ISSUE THREAD

**Issue by mzegar** [mzegar/sbox-TTT#38]
- Add methods for start using, stop using, etc.
- Separate any UI and "Use" functionality.
- Consider looking at ILook plus IUse, some combination

**Comment by youarereadingthis** [comment]
Don't know how S&box handles USE targeting, but in Source 1 it was common to not be able to use something you're directly looking at because of a hull tracing hitting something to the side of it. Very clunky.

Line tracing for TTT entities solves that.

**Comment by mzegar** [comment]
It's done.
