### ISSUE TITLE
Backstab Knife

### ISSUE THREAD

**Issue by youarereadingthis** [mzegar/sbox-TTT#39]
**Problem:**
- It's lame and brainless to instantly die at full health because someone got close to you and clicked anywhere on your body.
- The default 2-hit knife can still be effective but doesn't encourage much thought either and isn't very interesting to use.

**Solution:**
- Encourage sneaky play by making only backstabs instantly kill.
- To balance this, stabs from the front could take 2-3 hits. Faster attack speed.
- (Maybe) backstabs are silent but make sound from the front.

**Comment by mzegar** [comment]
We will do one left click to instantly kill, and see how it plays out. If it's too overpowered, we can balance it. There isn't a point in considering any balancing since we haven't done a playtest with all core mechanics in.
