### ISSUE TITLE
Newton Launcher Pull Mode

### ISSUE THREAD

**Issue by youarereadingthis** [mzegar/sbox-TTT#42]
- Press R to toggle Push/Pull modes. Changes first and thirdperson model color.
- It can pull physics objects(weapons/ammo included) and players to you.
- May help with round delays by cowardly nerds trying to not die or something.

**Also:**
- I suggest having it trace for player hulls and hitboxes to make it less reliant on poor (s)hit-detection.

**Comment by mzegar** [comment]
Re-open this once we actually have the vanilla game mode running, we can then consider further "vanilla" additions or changes to match source 2 gameplay.
