### ISSUE TITLE
Implement GMod TTT's (Unfinished) Beacon

### ISSUE THREAD

**Issue by youarereadingthis** [mzegar/sbox-TTT#43]
- There was a `weapon_ttt_beacon` entity that was never finished, though it's a good and simple idea.
- There exists an unfinished(?) screen icon in the files still: `vgui/ttt/det_beacon.vtf`
![det_beacon](https://user-images.githubusercontent.com/100040020/154865726-b967fbeb-cf67-487c-a91e-4c0b935362cd.png)

**Idea:**
- I assume how it was supposed to work is that you place it down and innocents see a 3D-pos screen icon for it on their HUD.
- For balance purposes I suggest having it take a few seconds to place down. Can't cheese a traitor during an ambush that way.
- It could also only make a fading blip every 10 seconds.

**Comment by mzegar** [comment]
Re-open this once we actually have the vanilla game mode running, we can then consider further "vanilla" additions or changes to match source 2 gameplay.
