### ISSUE TITLE
Alternate UMP On-Hit Effect

### ISSUE THREAD

**Issue by youarereadingthis** [mzegar/sbox-TTT#44]
**Problem:**
- The viewpunch is fucking annoying.
- Having it serverside causes seriously problematic desync with your aim direction.
- Having it clientside allows for cheating.
- Also the vanilla headshot multiplier is insanely high.
`SWEP.HeadshotMultiplier    = 4.5 -- brain fizz`

**Solution:**
- Remove the obnoxious on-hit viewpunch effect.
- The bullets contain trackers that alert you to their position each second for 7 seconds. (configurable)

**Comment by mzegar** [comment]
We open this once we get a UMP ingame. For now, this will not be done for a while.
