### ISSUE TITLE
Map Selection doesn't work

### ISSUE THREAD

**Issue by MNOGOZNAAL** [mzegar/sbox-TTT#51]
MapSelectionRound doesn't show a window with a choice of maps. Round ends with "No viable TTT-support maps found on server. Restarting game on default map."

**Comment by mzegar** [comment]
I think this is because the game isn't uploaded yet to FacePunch servers. We are still currently in the process of rewriting the entire game mode, pretty close to being done. Let me know if this occurs when FP servers are back up.

**Comment by mzegar** [comment]
Gamemode is back to being uploaded, and this was a separate bug that is now fixed, thank you for the bug report.
